INSERT INTO SHOPS(NAME, OPEN, MIN_ORDER_AMOUNT, COMMISSION_RATE) VALUES('오겹돼지', 1, 13000, 0.01);

INSERT INTO MENUS(SHOP_ID, FOOD_NAME, FOOD_PRICE, FOOD_DESCRIPTION) VALUES(1, '삼겹살 1인세트', 12000, '삼겹살 + 야채세트 + 김치찌개 + 공기밥1개');

INSERT INTO OPTION_GROUP_SPECS(MENU_ID, NAME, EXCLUSIVE, BASIC) VALUES(1, '기본', 1, 1);
INSERT INTO OPTION_SPECS(OPTION_GROUP_SPEC_ID, NAME, PRICE) VALUES(1, '소(250g)', 12000);
INSERT INTO OPTION_SPECS(OPTION_GROUP_SPEC_ID, NAME, PRICE) VALUES(1, '중(400g)', 16000);
INSERT INTO OPTION_SPECS(OPTION_GROUP_SPEC_ID, NAME, PRICE) VALUES(1, '대(600g)', 20000);

INSERT INTO OPTION_GROUP_SPECS(MENU_ID, NAME, EXCLUSIVE, BASIC) VALUES(1, '맛선택', 0, 0);
INSERT INTO OPTION_SPECS(OPTION_GROUP_SPEC_ID, NAME, PRICE) VALUES(2, '일반 맛', 0);
INSERT INTO OPTION_SPECS(OPTION_GROUP_SPEC_ID, NAME, PRICE) VALUES(2, '매콤 맛', 1000);

INSERT INTO OPTION_GROUP_SPECS(MENU_ID, NAME, EXCLUSIVE, BASIC) VALUES(1, '추가선택', 0, 0);
INSERT INTO OPTION_SPECS(OPTION_GROUP_SPEC_ID, NAME, PRICE) VALUES(3, '부추재래기 추가', 1000);
INSERT INTO OPTION_SPECS(OPTION_GROUP_SPEC_ID, NAME, PRICE) VALUES(3, '야채세트 추가', 1000);
INSERT INTO OPTION_SPECS(OPTION_GROUP_SPEC_ID, NAME, PRICE) VALUES(3, '고기(100g) 추가', 5000);

